repos:
  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: "v2.18.0"
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: "https://github.com/kynan/nbstripout"
    rev: "0.5.0"
    hooks:
      - id: nbstripout
        stages: [commit]
  - repo: "https://github.com/pre-commit/mirrors-prettier"
    rev: "v2.7.1"
    hooks:
      - id: prettier
        stages: [commit]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.5"
    hooks:
      # Run the linter.
      - id: ruff
        stages: [commit]
      # Run the formatter.
      - id: ruff-format
        stages: [commit]
